const SET_CHECKED = "SET_CHECKED";
const TOGGLE_MENU = "TOGGLE_MENU";
const DISPLAY_COLOR_PICKER = "DISPLAY_COLOR_PICKER";
const CLOSE_COLOR_PICKER = "CLOSE_COLOR_PICKER";
const CHANGE_COLOR = "CHANGE_COLOR";
const CONVERT_TO_HEX = "CONVERT_TO_HEX"